server:
  port: 8080

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/caffe_in?serverTimezone=Asia/Seoul
    username: ssafy
    password: ssafy
  jpa:
    open-in-view: false

logging.level.com.kql.caffein: debug

jwt:
  header: Authorization
  secret: miniboard
  token-validity-in-seconds: 86400 # 60 * 60 * 24